'use client';

import Link from 'next/link';
import { Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#08090a] text-white">
      <nav className="flex items-center justify-between px-6 py-4 border-b border-white/[0.04]">
        <Link href="/" className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-violet-600 to-purple-700 flex items-center justify-center">
            <Zap className="w-4 h-4 text-white" />
          </div>
          <span className="font-display font-bold text-white">AI Matchmaker</span>
        </Link>
        <Link href="/login"><Button variant="gradient" size="sm">Sign In</Button></Link>
      </nav>
      <main className="max-w-3xl mx-auto px-6 py-20">
        <h1 className="font-display text-4xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-10">Last updated: July 2025</p>
        <div className="space-y-8 text-white/60 text-sm leading-relaxed">
          <div><h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By using AI Matchmaker, you agree to these Terms. If you do not agree, do not use the platform.</p></div>
          <div><h2 className="text-lg font-semibold text-white mb-3">2. Use of Service</h2>
            <p>You agree to use AI Matchmaker only for lawful purposes. You are responsible for maintaining the accuracy of your profile information. Misrepresentation is grounds for account termination.</p></div>
          <div><h2 className="text-lg font-semibold text-white mb-3">3. AI-Generated Content</h2>
            <p>AI match scores, insights, and recommendations are generated by AI and are advisory in nature. AI Matchmaker is not responsible for outcomes of matches or hiring decisions.</p></div>
          <div><h2 className="text-lg font-semibold text-white mb-3">4. Intellectual Property</h2>
            <p>The AI Matchmaker platform, branding, and technology are owned by AI Matchmaker. User-provided profile content remains owned by the user.</p></div>
          <div><h2 className="text-lg font-semibold text-white mb-3">5. Limitation of Liability</h2>
            <p>AI Matchmaker provides matching services on a best-effort basis. We are not liable for direct, indirect, or consequential damages arising from use of the platform.</p></div>
        </div>
      </main>
    </div>
  );
}
